config/routes.rb
Gallery::Application.routes.draw do
  resources :paintings
  root to: 'paintings#index'
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :image, :name
  mount_uploader :image, ImageUploader
  
  after_save :enqueue_image
  
  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    ImageWorker.perform_async(id, key) if key.present?
  end

  class ImageWorker
    include Sidekiq::Worker
    
    def perform(id, key)
      painting = Painting.find(id)
      painting.key = key
      painting.remote_image_url = painting.image.direct_fog_url(with_path: true)
      painting.save!
      painting.update_column(:image_processed, true)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = Painting.all
    @uploader = Painting.new.image
    @uploader.success_action_redirect = new_painting_url
  end

  def show
    @painting = Painting.find(params[:id])
  end

  def new
    @painting = Painting.new(key: params[:key])
  end

  def create
    @painting = Painting.new(params[:painting])
    if @painting.save
      redirect_to paintings_url, notice: "Painting was successfully created."
    else
      render :new
    end
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      redirect_to paintings_url, notice: "Painting was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    redirect_to paintings_url, notice: "Painting was successfully destroyed."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/upload_helper.rb
def s3_uploader_form(options = {}, &block)
  uploader = S3Uploader.new(options)
  form_tag(uploader.url, uploader.form_options) do
    uploader.fields.map do |name, value|
    hidden_field_tag(name, value)
    end.join.html_safe + capture(&block)
  end
end

# def initialize(options)
#   @options = options.reverse_merge(
#     id: "fileupload",
#     aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
#     aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
#     bucket: ENV["AWS_S3_BUCKET"],
#     acl: "public-read",
#     expiration: 10.hours.from_now,
#     max_file_size: 500.megabytes,
#     as: "file"
#   )
# end

def policy
  Base64.encode64(policy_data.to_json).gsub("\n", "")
 end

def policy_data
  {
    expiration: @options[:expiration],
    conditions: [
      ["starts-with", "$utf8", ""],
      ["starts-with", "$key", ""],
      ["content-length-range", 0, @options[:max_file_size]],
      {bucket: @options[:bucket]},
      {acl: @options[:acl]}
    ]
  }
end

 def signature
  Base64.encode64(
    OpenSSL::HMAC.digest(
      OpenSSL::Digest::Digest.new('sha1'),
      @options[:aws_secret_access_key], policy
    )
  ).gsub("\n", "")
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Painting Gallery</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/paintings/_form.html.erb
<%= form_for @painting do |f| %>
  <!-- Validation code omitted -->

  <%= f.hidden_field :key %>

  <p>File: <%= @painting.image_name %></p>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<div class="painting">
  <% if painting.image_processed? %>
    <%= link_to image_tag(painting.image_url(:thumb)), painting %>
  <% else %>
    <em>Processing...</em>
  <% end %>
  <div class="name"><%= painting.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_painting_path(painting) %> |
    <%= link_to "remove", painting, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/paintings/edit.html.erb
<h1>Editing Painting</h1>

<%= render 'form' %>

app/views/paintings/index.html.erb
<h1>Painting Gallery</h1>

<div id="paintings">
  <%= render @paintings %>
</div>
<div class="clear"></div>

<%= s3_uploader_form post: paintings_url, as: "painting[image_url]" do %>
  <%= file_field_tag :file, multiple: true %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

app/views/paintings/new.html.erb
<h1>Add a Painting</h1>

<%= render 'form' %>

app/views/paintings/show.html.erb
<h1><%= @painting.name %></h1>

<p><%= image_tag @painting.image_url %></p>

<p>
  <%= link_to "Edit", edit_painting_path(@painting) %> |
  <%= link_to "Destroy", @painting, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to Paintings", paintings_path %>
</p>